CREATE TABLE Account_Master (
    AccountID INT PRIMARY KEY,
    AccountNumber VARCHAR(20) UNIQUE,
    CustomerID INT,
    AccountType VARCHAR(20),
    BranchCode VARCHAR(10),
    OpeningDate DATE,
    ClosingDate DATE,
    AccountStatus VARCHAR(20),
    CurrentBalance DECIMAL(15, 2),
    AvailableBalance DECIMAL(15, 2),
    OverdraftLimit DECIMAL(15, 2),
    InterestRate DECIMAL(5, 2),
    AccountCurrency VARCHAR(3),
    AccountManagerID INT,
    IsJointAccount BOOLEAN,
    NomineeName VARCHAR(100),
    NomineeRelation VARCHAR(50),
    LastTransactionDate DATE,
    AccountTier VARCHAR(20),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES Customer_Master(CustomerID)
);
