CREATE TABLE International_Payments (
    InternationalPaymentID INT PRIMARY KEY,
    CustomerID INT,
    AccountID INT,
    PaymentAmount DECIMAL(15, 2),
    PaymentDate DATE,
    PaymentCurrency VARCHAR(3),
    ExchangeRate DECIMAL(10, 6),
    ConvertedAmount DECIMAL(15, 2),
    BeneficiaryName VARCHAR(100),
    BeneficiaryAccountNumber VARCHAR(20),
    BeneficiaryBankName VARCHAR(100),
    BeneficiaryBankSWIFT VARCHAR(20),
    IntermediaryBankName VARCHAR(100),
    IntermediaryBankSWIFT VARCHAR(20),
    PaymentPurpose VARCHAR(255),
    RegulatoryCompliance VARCHAR(50),
    AMLCheckStatus VARCHAR(20),
    TransactionID INT,
    PaymentStatus VARCHAR(50), -- e.g., Completed, Pending, Failed
    ReferenceNumber VARCHAR(50),
    TransactionFees DECIMAL(10, 2),
    Notes TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES Customer_Master(CustomerID),
    FOREIGN KEY (AccountID) REFERENCES Account_Master(AccountID),
    FOREIGN KEY (TransactionID) REFERENCES Transaction_Master(TransactionID)
);
