CREATE TABLE Settlement_Data (
    SettlementID INT PRIMARY KEY,
    TransactionID VARCHAR(30),
    CustomerID INT,
    SettlementDate DATE,
    CurrencyCode VARCHAR(3),
    SettlementAmount DECIMAL(15, 2),
    FeeAmount DECIMAL(10, 2),
    NetAmount DECIMAL(15, 2),
    Status VARCHAR(20),
    PaymentMethod VARCHAR(50),
    BeneficiaryName VARCHAR(100),
    BeneficiaryAccountNumber VARCHAR(20),
    BeneficiaryBankName VARCHAR(100),
    BeneficiaryBankSWIFT VARCHAR(20),
    InitiatingParty VARCHAR(100),
    InitiatingPartyAccountNumber VARCHAR(20),
    InitiatingBankName VARCHAR(100),
    InitiatingBankSWIFT VARCHAR(20),
    ReferenceNumber VARCHAR(50),
    SettlementType VARCHAR(50),
    FXRate DECIMAL(10, 6),
    SettlementInstructions TEXT,
    CountryCode VARCHAR(3),
    BankCharges DECIMAL(10, 2),
    AdditionalInfo TEXT,
    ProcessingStatus VARCHAR(50),
    SettlementPriority VARCHAR(20),
    SettlementTime TIMESTAMP,
    TransactionSource VARCHAR(50),
    ClearingHouse VARCHAR(50),
    BatchID VARCHAR(50),
    AccountHolderType VARCHAR(20),
    AccountClass VARCHAR(20),
    LiquidityStatus VARCHAR(20),
    ConfirmationCode VARCHAR(50),
    ReconciliationStatus VARCHAR(20),
    ExceptionHandling VARCHAR(50),
    IntermediaryBank VARCHAR(100),
    IntermediaryBankSWIFT VARCHAR(20),
    ComplianceCheck VARCHAR(20),
    RegulatoryReporting VARCHAR(20),
    TaxInformation VARCHAR(255),
    PaymentPurpose VARCHAR(255),
    AMLCheckStatus VARCHAR(20),
    FraudCheckStatus VARCHAR(20),
    RiskAssessmentScore INT,
    PaymentReference VARCHAR(50),
    CounterpartyDetails VARCHAR(255),
    PaymentChannel VARCHAR(50),
    InvoiceReference VARCHAR(50),
    DisputeStatus VARCHAR(20),
    SettlementWindow VARCHAR(20),
    PaymentBatchReference VARCHAR(50),
    PaymentFrequency VARCHAR(20),
    PaymentCycle VARCHAR(20),
    LatePaymentIndicator BOOLEAN,
    PenaltyAmount DECIMAL(10, 2),
    SettlementMode VARCHAR(20),
    NostroAccount VARCHAR(50),
    VostroAccount VARCHAR(50),
    FXBookingReference VARCHAR(50),
    CorporateAction VARCHAR(50),
    InstructionType VARCHAR(50),
    SettlementVenue VARCHAR(100),
    OperationalNotes TEXT,
    CustomerInstructions TEXT,
    BankInstructions TEXT,
    CounterpartyInstructions TEXT,
    MarketConditions VARCHAR(50),
    SettlementDateTime TIMESTAMP,
    SettlementEffectiveDate DATE,
    RegulatoryApprovalStatus VARCHAR(20),
    InstructionPriority VARCHAR(20),
    IntermediaryInstructions TEXT,
    RiskMitigationMeasures VARCHAR(255),
    PaymentIdentificationCode VARCHAR(50),
    SWIFTMessageType VARCHAR(10),
    PaymentClearingMechanism VARCHAR(50),
    SettlementConfirmationStatus VARCHAR(20),
    RegulatoryComplianceStatus VARCHAR(20),
    PaymentSequenceNumber INT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES Customer_Master(CustomerID)
);
